
/* Drop Tables */

DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS EMAIL;
DROP TABLE IF EXISTS MEMBERSHIP;
DROP TABLE IF EXISTS GRP;
DROP TABLE IF EXISTS USR;




/* Create Tables */

-- 住所
CREATE TABLE ADDRESS
(
	-- ユーザID
	USER_ID bigint NOT NULL,
	-- 郵便番号
	ZIP_CODE varchar(8),
	-- 住所
	ADDRESS varchar,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_AT timestamp,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;


-- メール
CREATE TABLE EMAIL
(
	-- ユーザID
	USER_ID bigint NOT NULL,
	-- メール番号
	EMAIL_NO bigint NOT NULL,
	-- メールアドレス
	EMAIL varchar,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_AT timestamp,
	PRIMARY KEY (USER_ID, EMAIL_NO),
	UNIQUE (USER_ID, EMAIL_NO)
) WITHOUT OIDS;


-- グループ
CREATE TABLE GRP
(
	-- グループID
	GROUP_ID bigint NOT NULL,
	-- グループ名
	GROUP_NAME varchar,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_AT timestamp,
	PRIMARY KEY (GROUP_ID)
) WITHOUT OIDS;


-- 所属
CREATE TABLE MEMBERSHIP
(
	-- ユーザID
	USER_ID bigint NOT NULL,
	-- グループID
	GROUP_ID bigint NOT NULL,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_AT timestamp,
	PRIMARY KEY (USER_ID, GROUP_ID),
	UNIQUE (USER_ID, GROUP_ID)
) WITHOUT OIDS;


-- ユーザ
CREATE TABLE USR
(
	-- ユーザID
	USER_ID bigint NOT NULL,
	-- 名前
	FIRST_NAME varchar,
	-- 苗字
	FAMILY_NAME varchar,
	-- ログインID
	LOGIN_ID varchar UNIQUE,
	-- ログイン中
	IS_LOGIN boolean,
	-- バージョン
	VER int,
	-- 最終更新日時
	LAST_UPDATED_AT timestamp,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE MEMBERSHIP
	ADD FOREIGN KEY (GROUP_ID)
	REFERENCES GRP (GROUP_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ADDRESS
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMAIL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBERSHIP
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE ADDRESS IS '住所';
COMMENT ON COLUMN ADDRESS.USER_ID IS 'ユーザID';
COMMENT ON COLUMN ADDRESS.ZIP_CODE IS '郵便番号';
COMMENT ON COLUMN ADDRESS.ADDRESS IS '住所';
COMMENT ON COLUMN ADDRESS.VER IS 'バージョン';
COMMENT ON COLUMN ADDRESS.LAST_UPDATED_AT IS '最終更新日時';
COMMENT ON TABLE EMAIL IS 'メール';
COMMENT ON COLUMN EMAIL.USER_ID IS 'ユーザID';
COMMENT ON COLUMN EMAIL.EMAIL_NO IS 'メール番号';
COMMENT ON COLUMN EMAIL.EMAIL IS 'メールアドレス';
COMMENT ON COLUMN EMAIL.VER IS 'バージョン';
COMMENT ON COLUMN EMAIL.LAST_UPDATED_AT IS '最終更新日時';
COMMENT ON TABLE GRP IS 'グループ';
COMMENT ON COLUMN GRP.GROUP_ID IS 'グループID';
COMMENT ON COLUMN GRP.GROUP_NAME IS 'グループ名';
COMMENT ON COLUMN GRP.VER IS 'バージョン';
COMMENT ON COLUMN GRP.LAST_UPDATED_AT IS '最終更新日時';
COMMENT ON TABLE MEMBERSHIP IS '所属';
COMMENT ON COLUMN MEMBERSHIP.USER_ID IS 'ユーザID';
COMMENT ON COLUMN MEMBERSHIP.GROUP_ID IS 'グループID';
COMMENT ON COLUMN MEMBERSHIP.VER IS 'バージョン';
COMMENT ON COLUMN MEMBERSHIP.LAST_UPDATED_AT IS '最終更新日時';
COMMENT ON TABLE USR IS 'ユーザ';
COMMENT ON COLUMN USR.USER_ID IS 'ユーザID';
COMMENT ON COLUMN USR.FIRST_NAME IS '名前';
COMMENT ON COLUMN USR.FAMILY_NAME IS '苗字';
COMMENT ON COLUMN USR.LOGIN_ID IS 'ログインID';
COMMENT ON COLUMN USR.IS_LOGIN IS 'ログイン中';
COMMENT ON COLUMN USR.VER IS 'バージョン';
COMMENT ON COLUMN USR.LAST_UPDATED_AT IS '最終更新日時';
